version: '3.4'

services:
  sd.jatek.web:
    image: ${DOCKER_REGISTRY-}sdjatekweb
    build:
      context: .
      dockerfile: Jatek/sd.Jatek.Web/Dockerfile
    depends_on:
      sql-server-db:
        condition: service_started
      rabbitmq :
        condition: service_started
    healthcheck:
      test: curl --fail-with-body http://localhost:5005/_health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  sd.statisztika.web:
    image: ${DOCKER_REGISTRY-}sdstatisztikaweb
    build:
      context: .
      dockerfile: Statisztika/sd.Statisztika.Web/Dockerfile
    depends_on:
      sql-server-db:
        condition: service_started
      rabbitmq :
        condition: service_started
    healthcheck:
      test: curl --fail-with-body http://localhost:5031/_health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  sd.apigateway.web:
    image: ${DOCKER_REGISTRY-}sdapigatewayweb
    build:
      context: .
      dockerfile: ApiGateway/sd.ApiGateway.Web/Dockerfile
    depends_on:
      - sql-server-db
    healthcheck:
      test: curl --fail-with-body http://localhost/_health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  sd.auth.web:
    image: ${DOCKER_REGISTRY-}sdauthweb
    build:
      context: .
      dockerfile: Auth/sd.Auth.Web/Dockerfile
    depends_on:
      - sql-server-db
    healthcheck:
      test: curl --fail-with-body http://localhost:5011/_health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672  

  redis:
    image: redis