version: '3.4'

services:

   test-auth:
     build:
       context: .
       dockerfile: ../finalsd/Auth/sd.Auth.Web/Dockerfile
     ports: 
       - "5011:5011"
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5011
       - SqlServer_ConnectionString=Data Source=sql-test-db,1422;Initial Catalog=msdb;User ID=sa;Password=Pass@word; TrustServerCertificate=true
   
   test-db:
     container_name: sql-test-db
     image: mcr.microsoft.com/mssql/server
     restart: always
     environment:
       SA_PASSWORD: "Pass@word"
       ACCEPT_EULA: "Y"
     ports:
        - "1422:1422"